<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230618100613 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE abonnement_boutique_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE boutique_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE boutique_object_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE category_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE commande_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE commission_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE compte_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE connexion_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE historique_paiement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE jwt_refresh_token_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE like_produit_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE list_commande_livreur_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE list_produit_panier_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE list_produit_promotion_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE localisation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE message_negociation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE mode_paiement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE negociation_produit_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE notation_boutique_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE panier_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE point_livraison_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE produit_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE produit_object_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE promotion_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE short_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE transaction_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_commande_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_paiement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_transaction_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_user_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE user_plateform_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE abonnement_boutique (id INT NOT NULL, boutique_id INT DEFAULT NULL, client_id INT DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E22B8783AB677BE6 ON abonnement_boutique (boutique_id)');
        $this->addSql('CREATE INDEX IDX_E22B878319EB6921 ON abonnement_boutique (client_id)');
        $this->addSql('CREATE TABLE boutique (id INT NOT NULL, user_id INT DEFAULT NULL, localisation_id INT DEFAULT NULL, category_id INT DEFAULT NULL, titre VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, status BOOLEAN NOT NULL, code_boutique VARCHAR(255) DEFAULT NULL, date_created DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A1223C54A76ED395 ON boutique (user_id)');
        $this->addSql('CREATE INDEX IDX_A1223C54C68BE09C ON boutique (localisation_id)');
        $this->addSql('CREATE INDEX IDX_A1223C5412469DE2 ON boutique (category_id)');
        $this->addSql('CREATE TABLE boutique_object (id INT NOT NULL, boutique_id INT DEFAULT NULL, src VARCHAR(255) NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BB6A4419AB677BE6 ON boutique_object (boutique_id)');
        $this->addSql('CREATE TABLE category (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, date_created DATE NOT NULL, status BOOLEAN NOT NULL, logo VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19C1A4D60759 ON category (libelle)');
        $this->addSql('CREATE TABLE commande (id INT NOT NULL, mode_paiement_id INT DEFAULT NULL, panier_id INT DEFAULT NULL, point_livraison_id INT DEFAULT NULL, type_commande_id INT DEFAULT NULL, titre VARCHAR(255) NOT NULL, description VARCHAR(10000) DEFAULT NULL, date_created DATE NOT NULL, code_commande VARCHAR(255) NOT NULL, code_client VARCHAR(255) NOT NULL, status_buy BOOLEAN NOT NULL, status_finish INT NOT NULL, token TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6EEAA67D438F5B63 ON commande (mode_paiement_id)');
        $this->addSql('CREATE INDEX IDX_6EEAA67DF77D927C ON commande (panier_id)');
        $this->addSql('CREATE INDEX IDX_6EEAA67D78DB0241 ON commande (point_livraison_id)');
        $this->addSql('CREATE INDEX IDX_6EEAA67DC9F3F9C5 ON commande (type_commande_id)');
        $this->addSql('CREATE TABLE commission (id INT NOT NULL, pourcentage_produit DOUBLE PRECISION DEFAULT NULL, frais_livraison_produit DOUBLE PRECISION NOT NULL, frais_buy_livreur DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE compte (id INT NOT NULL, user_id INT DEFAULT NULL, solde INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CFF65260A76ED395 ON compte (user_id)');
        $this->addSql('CREATE TABLE connexion (id INT NOT NULL, user_id INT DEFAULT NULL, date_in TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_out TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_agent VARCHAR(255) NOT NULL, ip VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_936BF99CA76ED395 ON connexion (user_id)');
        $this->addSql('CREATE TABLE historique_paiement (id INT NOT NULL, user_id INT DEFAULT NULL, type_paiement_id INT DEFAULT NULL, commande_id INT DEFAULT NULL, montant VARCHAR(255) NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, token VARCHAR(255) NOT NULL, status BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_710402ECA76ED395 ON historique_paiement (user_id)');
        $this->addSql('CREATE INDEX IDX_710402EC615593E9 ON historique_paiement (type_paiement_id)');
        $this->addSql('CREATE INDEX IDX_710402EC82EA2E54 ON historique_paiement (commande_id)');
        $this->addSql('CREATE TABLE jwt_refresh_token (id INT NOT NULL, refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_expire_token TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F3D9535C74F2195 ON jwt_refresh_token (refresh_token)');
        $this->addSql('CREATE TABLE like_produit (id INT NOT NULL, client_id INT DEFAULT NULL, produit_id INT DEFAULT NULL, like_produit BOOLEAN NOT NULL, date_created DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7A28A60419EB6921 ON like_produit (client_id)');
        $this->addSql('CREATE INDEX IDX_7A28A604F347EFB ON like_produit (produit_id)');
        $this->addSql('CREATE TABLE list_commande_livreur (id INT NOT NULL, commande_id INT DEFAULT NULL, livreur_id INT DEFAULT NULL, date_created DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A629619382EA2E54 ON list_commande_livreur (commande_id)');
        $this->addSql('CREATE INDEX IDX_A6296193F8646701 ON list_commande_livreur (livreur_id)');
        $this->addSql('CREATE TABLE list_produit_panier (id INT NOT NULL, panier_id INT DEFAULT NULL, produit_id INT DEFAULT NULL, status BOOLEAN NOT NULL, quantite INT NOT NULL, code_produit_panier VARCHAR(255) NOT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, prix_unitaire_vente INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AAC86140F77D927C ON list_produit_panier (panier_id)');
        $this->addSql('CREATE INDEX IDX_AAC86140F347EFB ON list_produit_panier (produit_id)');
        $this->addSql('CREATE TABLE list_produit_promotion (id INT NOT NULL, produit_id INT DEFAULT NULL, promotion_id INT DEFAULT NULL, date_created DATE NOT NULL, prix_promotion INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C9E2B793F347EFB ON list_produit_promotion (produit_id)');
        $this->addSql('CREATE INDEX IDX_C9E2B793139DF194 ON list_produit_promotion (promotion_id)');
        $this->addSql('CREATE TABLE localisation (id INT NOT NULL, user_id INT DEFAULT NULL, ville VARCHAR(1000) DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, ip VARCHAR(255) DEFAULT NULL, date_in TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BFD3CE8FA76ED395 ON localisation (user_id)');
        $this->addSql('CREATE TABLE message_negociation (id INT NOT NULL, negociation_id INT DEFAULT NULL, emetteur BOOLEAN NOT NULL, message TEXT NOT NULL, date_envoi TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D59E6921A2D1D3D7 ON message_negociation (negociation_id)');
        $this->addSql('CREATE TABLE mode_paiement (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE negociation_produit (id INT NOT NULL, produit_id INT DEFAULT NULL, initiateur_id INT DEFAULT NULL, code_negociation VARCHAR(255) DEFAULT NULL, prix_negocie VARCHAR(255) DEFAULT NULL, date_created TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E0EEB46CF347EFB ON negociation_produit (produit_id)');
        $this->addSql('CREATE INDEX IDX_E0EEB46C56D142FC ON negociation_produit (initiateur_id)');
        $this->addSql('CREATE TABLE notation_boutique (id INT NOT NULL, client_id INT DEFAULT NULL, boutique_id INT DEFAULT NULL, note DOUBLE PRECISION NOT NULL, date_created DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7B281E2419EB6921 ON notation_boutique (client_id)');
        $this->addSql('CREATE INDEX IDX_7B281E24AB677BE6 ON notation_boutique (boutique_id)');
        $this->addSql('CREATE TABLE panier (id INT NOT NULL, user_id INT DEFAULT NULL, date_created DATE DEFAULT NULL, code_panier VARCHAR(255) NOT NULL, nom_client VARCHAR(255) NOT NULL, prenom_client VARCHAR(255) DEFAULT NULL, phone_client VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_24CC0DF2A76ED395 ON panier (user_id)');
        $this->addSql('CREATE TABLE point_livraison (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, ville VARCHAR(255) NOT NULL, quartier VARCHAR(255) NOT NULL, image VARCHAR(255) DEFAULT NULL, status BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE produit (id INT NOT NULL, category_id INT DEFAULT NULL, boutique_id INT DEFAULT NULL, titre VARCHAR(255) NOT NULL, description VARCHAR(10000) DEFAULT NULL, date_created DATE NOT NULL, prix_unitaire INT NOT NULL, quantite INT NOT NULL, status BOOLEAN NOT NULL, code_produit VARCHAR(255) NOT NULL, taille INT DEFAULT NULL, negociable BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_29A5EC2712469DE2 ON produit (category_id)');
        $this->addSql('CREATE INDEX IDX_29A5EC27AB677BE6 ON produit (boutique_id)');
        $this->addSql('CREATE TABLE produit_object (id INT NOT NULL, produit_id INT DEFAULT NULL, src TEXT NOT NULL, date_created DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5FFF60D6F347EFB ON produit_object (produit_id)');
        $this->addSql('CREATE TABLE promotion (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, date_created DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE short (id INT NOT NULL, boutique_id INT DEFAULT NULL, src VARCHAR(255) NOT NULL, titre VARCHAR(255) NOT NULL, status BOOLEAN NOT NULL, description VARCHAR(10000) DEFAULT NULL, date_created DATE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8F2890A2AB677BE6 ON short (boutique_id)');
        $this->addSql('CREATE TABLE transaction (id INT NOT NULL, client_id INT DEFAULT NULL, panier_id INT DEFAULT NULL, mode_paiement_id INT DEFAULT NULL, type_transaction_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, montant INT NOT NULL, token VARCHAR(255) NOT NULL, date_create TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status BOOLEAN NOT NULL, nom_client VARCHAR(255) NOT NULL, prenom_client VARCHAR(255) NOT NULL, numero_client VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_723705D119EB6921 ON transaction (client_id)');
        $this->addSql('CREATE INDEX IDX_723705D1F77D927C ON transaction (panier_id)');
        $this->addSql('CREATE INDEX IDX_723705D1438F5B63 ON transaction (mode_paiement_id)');
        $this->addSql('CREATE INDEX IDX_723705D17903E29B ON transaction (type_transaction_id)');
        $this->addSql('CREATE TABLE type_commande (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE type_paiement (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE type_transaction (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE type_user (id INT NOT NULL, libelle VARCHAR(255) NOT NULL, status BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE user_plateform (id INT NOT NULL, type_user_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, roles JSON NOT NULL, phone INT NOT NULL, status BOOLEAN NOT NULL, password VARCHAR(255) NOT NULL, date_created DATE NOT NULL, key_secret TEXT DEFAULT NULL, code_parrain VARCHAR(255) DEFAULT NULL, code_recup VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E623D83444F97DD ON user_plateform (phone)');
        $this->addSql('CREATE INDEX IDX_E623D838F4FBC60 ON user_plateform (type_user_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGSERIAL NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('CREATE OR REPLACE FUNCTION notify_messenger_messages() RETURNS TRIGGER AS $$
            BEGIN
                PERFORM pg_notify(\'messenger_messages\', NEW.queue_name::text);
                RETURN NEW;
            END;
        $$ LANGUAGE plpgsql;');
        $this->addSql('DROP TRIGGER IF EXISTS notify_trigger ON messenger_messages;');
        $this->addSql('CREATE TRIGGER notify_trigger AFTER INSERT OR UPDATE ON messenger_messages FOR EACH ROW EXECUTE PROCEDURE notify_messenger_messages();');
        $this->addSql('ALTER TABLE abonnement_boutique ADD CONSTRAINT FK_E22B8783AB677BE6 FOREIGN KEY (boutique_id) REFERENCES boutique (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE abonnement_boutique ADD CONSTRAINT FK_E22B878319EB6921 FOREIGN KEY (client_id) REFERENCES user_plateform (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE boutique ADD CONSTRAINT FK_A1223C54A76ED395 FOREIGN KEY (user_id) REFERENCES user_plateform (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE boutique ADD CONSTRAINT FK_A1223C54C68BE09C FOREIGN KEY (localisation_id) REFERENCES localisation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE boutique ADD CONSTRAINT FK_A1223C5412469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE boutique_object ADD CONSTRAINT FK_BB6A4419AB677BE6 FOREIGN KEY (boutique_id) REFERENCES boutique (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67D438F5B63 FOREIGN KEY (mode_paiement_id) REFERENCES mode_paiement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67DF77D927C FOREIGN KEY (panier_id) REFERENCES panier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67D78DB0241 FOREIGN KEY (point_livraison_id) REFERENCES point_livraison (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67DC9F3F9C5 FOREIGN KEY (type_commande_id) REFERENCES type_commande (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE compte ADD CONSTRAINT FK_CFF65260A76ED395 FOREIGN KEY (user_id) REFERENCES user_plateform (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE connexion ADD CONSTRAINT FK_936BF99CA76ED395 FOREIGN KEY (user_id) REFERENCES user_plateform (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE historique_paiement ADD CONSTRAINT FK_710402ECA76ED395 FOREIGN KEY (user_id) REFERENCES user_plateform (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE historique_paiement ADD CONSTRAINT FK_710402EC615593E9 FOREIGN KEY (type_paiement_id) REFERENCES type_paiement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE historique_paiement ADD CONSTRAINT FK_710402EC82EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE like_produit ADD CONSTRAINT FK_7A28A60419EB6921 FOREIGN KEY (client_id) REFERENCES user_plateform (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE like_produit ADD CONSTRAINT FK_7A28A604F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE list_commande_livreur ADD CONSTRAINT FK_A629619382EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE list_commande_livreur ADD CONSTRAINT FK_A6296193F8646701 FOREIGN KEY (livreur_id) REFERENCES user_plateform (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE list_produit_panier ADD CONSTRAINT FK_AAC86140F77D927C FOREIGN KEY (panier_id) REFERENCES panier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE list_produit_panier ADD CONSTRAINT FK_AAC86140F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE list_produit_promotion ADD CONSTRAINT FK_C9E2B793F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE list_produit_promotion ADD CONSTRAINT FK_C9E2B793139DF194 FOREIGN KEY (promotion_id) REFERENCES promotion (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE localisation ADD CONSTRAINT FK_BFD3CE8FA76ED395 FOREIGN KEY (user_id) REFERENCES user_plateform (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE message_negociation ADD CONSTRAINT FK_D59E6921A2D1D3D7 FOREIGN KEY (negociation_id) REFERENCES negociation_produit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE negociation_produit ADD CONSTRAINT FK_E0EEB46CF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE negociation_produit ADD CONSTRAINT FK_E0EEB46C56D142FC FOREIGN KEY (initiateur_id) REFERENCES user_plateform (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notation_boutique ADD CONSTRAINT FK_7B281E2419EB6921 FOREIGN KEY (client_id) REFERENCES user_plateform (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notation_boutique ADD CONSTRAINT FK_7B281E24AB677BE6 FOREIGN KEY (boutique_id) REFERENCES boutique (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE panier ADD CONSTRAINT FK_24CC0DF2A76ED395 FOREIGN KEY (user_id) REFERENCES user_plateform (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE produit ADD CONSTRAINT FK_29A5EC2712469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE produit ADD CONSTRAINT FK_29A5EC27AB677BE6 FOREIGN KEY (boutique_id) REFERENCES boutique (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE produit_object ADD CONSTRAINT FK_5FFF60D6F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE short ADD CONSTRAINT FK_8F2890A2AB677BE6 FOREIGN KEY (boutique_id) REFERENCES boutique (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D119EB6921 FOREIGN KEY (client_id) REFERENCES user_plateform (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1F77D927C FOREIGN KEY (panier_id) REFERENCES panier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1438F5B63 FOREIGN KEY (mode_paiement_id) REFERENCES mode_paiement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D17903E29B FOREIGN KEY (type_transaction_id) REFERENCES type_transaction (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_plateform ADD CONSTRAINT FK_E623D838F4FBC60 FOREIGN KEY (type_user_id) REFERENCES type_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('DROP SEQUENCE abonnement_boutique_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE boutique_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE boutique_object_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE category_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE commande_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE commission_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE compte_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE connexion_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE historique_paiement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE jwt_refresh_token_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE like_produit_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE list_commande_livreur_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE list_produit_panier_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE list_produit_promotion_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE localisation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE message_negociation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE mode_paiement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE negociation_produit_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE notation_boutique_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE panier_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE point_livraison_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE produit_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE produit_object_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE promotion_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE short_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE transaction_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_commande_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_paiement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_transaction_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_user_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE user_plateform_id_seq CASCADE');
        $this->addSql('ALTER TABLE abonnement_boutique DROP CONSTRAINT FK_E22B8783AB677BE6');
        $this->addSql('ALTER TABLE abonnement_boutique DROP CONSTRAINT FK_E22B878319EB6921');
        $this->addSql('ALTER TABLE boutique DROP CONSTRAINT FK_A1223C54A76ED395');
        $this->addSql('ALTER TABLE boutique DROP CONSTRAINT FK_A1223C54C68BE09C');
        $this->addSql('ALTER TABLE boutique DROP CONSTRAINT FK_A1223C5412469DE2');
        $this->addSql('ALTER TABLE boutique_object DROP CONSTRAINT FK_BB6A4419AB677BE6');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67D438F5B63');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67DF77D927C');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67D78DB0241');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67DC9F3F9C5');
        $this->addSql('ALTER TABLE compte DROP CONSTRAINT FK_CFF65260A76ED395');
        $this->addSql('ALTER TABLE connexion DROP CONSTRAINT FK_936BF99CA76ED395');
        $this->addSql('ALTER TABLE historique_paiement DROP CONSTRAINT FK_710402ECA76ED395');
        $this->addSql('ALTER TABLE historique_paiement DROP CONSTRAINT FK_710402EC615593E9');
        $this->addSql('ALTER TABLE historique_paiement DROP CONSTRAINT FK_710402EC82EA2E54');
        $this->addSql('ALTER TABLE like_produit DROP CONSTRAINT FK_7A28A60419EB6921');
        $this->addSql('ALTER TABLE like_produit DROP CONSTRAINT FK_7A28A604F347EFB');
        $this->addSql('ALTER TABLE list_commande_livreur DROP CONSTRAINT FK_A629619382EA2E54');
        $this->addSql('ALTER TABLE list_commande_livreur DROP CONSTRAINT FK_A6296193F8646701');
        $this->addSql('ALTER TABLE list_produit_panier DROP CONSTRAINT FK_AAC86140F77D927C');
        $this->addSql('ALTER TABLE list_produit_panier DROP CONSTRAINT FK_AAC86140F347EFB');
        $this->addSql('ALTER TABLE list_produit_promotion DROP CONSTRAINT FK_C9E2B793F347EFB');
        $this->addSql('ALTER TABLE list_produit_promotion DROP CONSTRAINT FK_C9E2B793139DF194');
        $this->addSql('ALTER TABLE localisation DROP CONSTRAINT FK_BFD3CE8FA76ED395');
        $this->addSql('ALTER TABLE message_negociation DROP CONSTRAINT FK_D59E6921A2D1D3D7');
        $this->addSql('ALTER TABLE negociation_produit DROP CONSTRAINT FK_E0EEB46CF347EFB');
        $this->addSql('ALTER TABLE negociation_produit DROP CONSTRAINT FK_E0EEB46C56D142FC');
        $this->addSql('ALTER TABLE notation_boutique DROP CONSTRAINT FK_7B281E2419EB6921');
        $this->addSql('ALTER TABLE notation_boutique DROP CONSTRAINT FK_7B281E24AB677BE6');
        $this->addSql('ALTER TABLE panier DROP CONSTRAINT FK_24CC0DF2A76ED395');
        $this->addSql('ALTER TABLE produit DROP CONSTRAINT FK_29A5EC2712469DE2');
        $this->addSql('ALTER TABLE produit DROP CONSTRAINT FK_29A5EC27AB677BE6');
        $this->addSql('ALTER TABLE produit_object DROP CONSTRAINT FK_5FFF60D6F347EFB');
        $this->addSql('ALTER TABLE short DROP CONSTRAINT FK_8F2890A2AB677BE6');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D119EB6921');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D1F77D927C');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D1438F5B63');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D17903E29B');
        $this->addSql('ALTER TABLE user_plateform DROP CONSTRAINT FK_E623D838F4FBC60');
        $this->addSql('DROP TABLE abonnement_boutique');
        $this->addSql('DROP TABLE boutique');
        $this->addSql('DROP TABLE boutique_object');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE commande');
        $this->addSql('DROP TABLE commission');
        $this->addSql('DROP TABLE compte');
        $this->addSql('DROP TABLE connexion');
        $this->addSql('DROP TABLE historique_paiement');
        $this->addSql('DROP TABLE jwt_refresh_token');
        $this->addSql('DROP TABLE like_produit');
        $this->addSql('DROP TABLE list_commande_livreur');
        $this->addSql('DROP TABLE list_produit_panier');
        $this->addSql('DROP TABLE list_produit_promotion');
        $this->addSql('DROP TABLE localisation');
        $this->addSql('DROP TABLE message_negociation');
        $this->addSql('DROP TABLE mode_paiement');
        $this->addSql('DROP TABLE negociation_produit');
        $this->addSql('DROP TABLE notation_boutique');
        $this->addSql('DROP TABLE panier');
        $this->addSql('DROP TABLE point_livraison');
        $this->addSql('DROP TABLE produit');
        $this->addSql('DROP TABLE produit_object');
        $this->addSql('DROP TABLE promotion');
        $this->addSql('DROP TABLE short');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE type_commande');
        $this->addSql('DROP TABLE type_paiement');
        $this->addSql('DROP TABLE type_transaction');
        $this->addSql('DROP TABLE type_user');
        $this->addSql('DROP TABLE user_plateform');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
